version: '3'
services:
  mdbook:
    build: .
    tty: true
    stdin_open: true
    ports:
      - "13000:3000"
    volumes:
      - ./documents:/md_book/src
    command:
      - serve
      - --hostname
      - "0.0.0.0"